[versions]
activity = "1.12.4"
agp = "8.11.2"
composeBom = "2026.02.00"
constraintlayout = "2.2.1"
fragmentKtx = "1.8.9"
kotlin = "2.3.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
legacySupportV4 = "1.0.0"
lifecycleRuntimeKtx = "2.10.0"
material = "1.13.0"
recyclerview = "1.4.0"
roomVersion = "2.8.4"
workRuntimeKtx = "2.11.1"
lifecycleService = "2.10.0"
androidx-emoji2 = "1.4.0"
androidx-paging = "3.4.1"
hilt = "2.57.2"
google-services = "4.4.4"
firebase-messaging = "25.0.1"
okhttp = "5.3.2"
retrofit = "3.0.0"
moshi = "1.15.2"
socket-io = "2.1.2"
glide = "5.0.5"
picture-selector = "v3.11.2"
exoplayer = "2.19.1"
subsampling-view = "3.10.0"
waveform-seekbar = "5.0.2"
amplituda = "2.3.1"
tink = "1.20.0"
bouncycastle = "1.70"
codeview = "1.3.9"
ksp = "2.3.5"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }
kotlin-metadata-jvm = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
socket-io-client = { module = "io.socket:socket.io-client", version.ref = "socket-io" }
picture-selector = { module = "io.github.lucksiege:pictureselector", version.ref = "picture-selector" }
picture-selector-compress = { module = "io.github.lucksiege:compress", version.ref = "picture-selector" }
picture-selector-ucrop = { module = "io.github.lucksiege:ucrop", version.ref = "picture-selector" }
picture-selector-camerax = { module = "io.github.lucksiege:camerax", version.ref = "picture-selector" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
emoji2-views = { module = "androidx.emoji2:emoji2-views", version.ref = "androidx-emoji2" }
emoji2-bundled = { module = "androidx.emoji2:emoji2-bundled", version.ref = "androidx-emoji2" }
emoji2-emojipicker = { module = "androidx.emoji2:emoji2-emojipicker", version.ref = "androidx-emoji2" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
paging-common-ktx = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
waveform-seekbar = { module = "com.github.massoudss:waveformSeekBar", version.ref = "waveform-seekbar" }
amplituda = { module = "com.github.lincollincol:amplituda", version.ref = "amplituda" }
subsampling-scale-image-view = { module = "com.davemorrissey.labs:subsampling-scale-image-view", version.ref = "subsampling-view" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }
tink-android = { module = "com.google.crypto.tink:tink-android", version.ref = "tink" }
bouncycastle-prov = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncycastle" }
bouncycastle-pkix = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncycastle" }
codeview = { module = "io.github.amrdeveloper:codeview", version.ref = "codeview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "kotlin-parcelize" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }